"""add city\conference\topic

Revision ID: 125e2c422af7
Revises: 4993b7bd6938
Create Date: 2015-11-26 23:23:50.501676

"""

# revision identifiers, used by Alembic.
revision = '125e2c422af7'
down_revision = '4993b7bd6938'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conferences', sa.Column('city_id', sa.Integer(), nullable=True))
    op.add_column('conferences', sa.Column('topic_ids', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'conferences', type_='foreignkey')
    op.drop_constraint(None, 'conferences', type_='foreignkey')
    op.create_foreign_key(None, 'conferences', 'topics', ['topic_ids'], ['id'])
    op.create_foreign_key(None, 'conferences', 'cities', ['city_id'], ['id'])
    op.drop_column('conferences', 'city')
    op.drop_column('conferences', 'topics')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conferences', sa.Column('topics', sa.INTEGER(), nullable=True))
    op.add_column('conferences', sa.Column('city', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'conferences', type_='foreignkey')
    op.drop_constraint(None, 'conferences', type_='foreignkey')
    op.create_foreign_key(None, 'conferences', 'cities', ['city'], ['id'])
    op.create_foreign_key(None, 'conferences', 'topics', ['topics'], ['id'])
    op.drop_column('conferences', 'topic_ids')
    op.drop_column('conferences', 'city_id')
    ### end Alembic commands ###
