"""review model of conference

Revision ID: bde2181a843
Revises: 22806fd2bb1
Create Date: 2015-12-05 20:22:00.359588

"""

# revision identifiers, used by Alembic.
revision = 'bde2181a843'
down_revision = '22806fd2bb1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conferences', sa.Column('attendees', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conferences', 'attendees')
    ### end Alembic commands ###
